//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ideation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ideation.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Division.
        /// </summary>
        public static string Err_Msg_DivisionId {
            get {
                return ResourceManager.GetString("Err_Msg_DivisionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Email.
        /// </summary>
        public static string Err_Msg_EmailId {
            get {
                return ResourceManager.GetString("Err_Msg_EmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select HUB.
        /// </summary>
        public static string Err_Msg_HUBId {
            get {
                return ResourceManager.GetString("Err_Msg_HUBId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Valid Email Id.
        /// </summary>
        public static string Err_Msg_Invalid_EmailId {
            get {
                return ResourceManager.GetString("Err_Msg_Invalid_EmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Login Id.
        /// </summary>
        public static string Err_Msg_LoginId {
            get {
                return ResourceManager.GetString("Err_Msg_LoginId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Manager.
        /// </summary>
        public static string Err_Msg_ManagerId {
            get {
                return ResourceManager.GetString("Err_Msg_ManagerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Classification.
        /// </summary>
        public static string Err_Msg_ProjectClassification {
            get {
                return ResourceManager.GetString("Err_Msg_ProjectClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Project Code.
        /// </summary>
        public static string Err_Msg_ProjectCode {
            get {
                return ResourceManager.GetString("Err_Msg_ProjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Project Division.
        /// </summary>
        public static string Err_Msg_ProjectDivision {
            get {
                return ResourceManager.GetString("Err_Msg_ProjectDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Project HUB.
        /// </summary>
        public static string Err_Msg_ProjectHUB {
            get {
                return ResourceManager.GetString("Err_Msg_ProjectHUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Project Manager.
        /// </summary>
        public static string Err_Msg_ProjectManager {
            get {
                return ResourceManager.GetString("Err_Msg_ProjectManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Project Name.
        /// </summary>
        public static string Err_Msg_ProjectName {
            get {
                return ResourceManager.GetString("Err_Msg_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Status.
        /// </summary>
        public static string Err_Msg_ProjectStatus {
            get {
                return ResourceManager.GetString("Err_Msg_ProjectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Project Type.
        /// </summary>
        public static string Err_Msg_ProjectType {
            get {
                return ResourceManager.GetString("Err_Msg_ProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select R&amp;D Team.
        /// </summary>
        public static string Err_Msg_RNDTeam {
            get {
                return ResourceManager.GetString("Err_Msg_RNDTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter User Name.
        /// </summary>
        public static string Err_Msg_UserName {
            get {
                return ResourceManager.GetString("Err_Msg_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select User Type.
        /// </summary>
        public static string Err_Msg_UserType {
            get {
                return ResourceManager.GetString("Err_Msg_UserType", resourceCulture);
            }
        }
    }
}
